### ISSUE TITLE
subject id type supported

### ISSUE THREAD

**Issue by Sakurann** [mattrglobal/oidc-portable-identities#5]
Currently, support for DIDs and concrete DID method supported are communicated separately. For example, `"subject_id_types_supported": ["did"], "did_methods supported": ["peer", "ion"]`

Would communicating did methods directly in `subject_id_types_supported` make it simpler?
`"subject_id_types_supported": ["did:peer:", "did:ion:"]`

**Comment by awoie** [comment]
i created a PR that might address that issue
